version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src:cached
      - ./package.json:/app/package.json:cached
      - ./tsconfig.json:/app/tsconfig.json:cached
      - ./knexfile.ts:/app/knexfile.ts:cached
      - app-node-modules:/app/node_modules
    ports:
      - "3333:3333"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
            - "**/*.test.ts"
        - action: rebuild
          path: package.json
          target: /app/package.json

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  app-node-modules: 